### PR TITLE
Named parameters

### PR DESCRIPTION
**Pull request by hsjoberg**
Hi!
This pull request changes the `DB.query` method to support [named parameters](https://tool.oschina.net/uploads/apidocs/sqlite/c3ref/bind_blob.html).

Instead of relying on the rest parameter (`...values`), a second parameter is added to `query`, which should be an object mapping each named parameter to a value:

```
db.query(
  "INSERT INTO tbl (a) value (:val)",
  { val: 123 }
)
```

This mimicks named placeholders of the [`mysql2`](https://github.com/sidorares/node-mysql2/blob/master/documentation/Extras.md#named-placeholders) npm package

I ran the benchmarking file (bench.ts) and saw no degradation in performance at all.

This is a **breaking change**, as the old method of using the rest parameter is not supported anymore. It's your project so you decide what you want to do, but in my opinion and by experience it makes sense to use named placeholders.
If you wish to support both, I guess the `query` method could be overloaded.

Regarding the WASM-file:
I have *not* included it in this commit as I'm unsure how to compile it using the `Makefile` of the project.
When I do a normal `make`, the exported `sqlite.wasm` does not contain any symbols other than `free`, `malloc`, and `memory`, so for some reason it seems like `KEEPALIVE` is not respected...
So, to be able to test this feature out, I ran with `-Wl,--export-all`.
I am allowing "Allow edits from maintainers" in this PR if you want to provide the WASM binary, otherwise tell me how I should compile it and I'll do it. :)
I'm using latest the emscripten SDK with llvm 10 (the binaries provided by the SDK).

Cheers!
Hampus

### CODE REVIEW

**Comment by dyedgreen** [comment]
@hsjoberg I had some time and went through your changes to update them according to #6. I'll wait with merging, until you had a chance to look over it.

(There seems to be a problem with running the CI if I push to your branch, but the tests etc are passing.)

**Comment by hsjoberg** [comment]
@dyedgreen Great, I will hopefully have time to look at it tomorrow. 😄

**Comment by hsjoberg** [comment]
> Just wen through again and noticed a few things. Will probably fix them later today. (You are also free to fix them, if you want @hsjoberg)

@dyedgreen Sorry, I don't have time today. Fix them you if you want to. 😄 
I'll hopefully have time to tomorrow to go through everything.

**Comment by dyedgreen** [comment]
Nudge @hsjoberg 😅

I want to merge these changes by the end of this week. If you cant look over them by then, I'd encurage you to open issues for anything that falls through the cracks.

Thank you again for your time and for submitting the PR!

**Comment by hsjoberg** [comment]
@dyedgreen Sorry for stalling this one. :sweat_smile:
I'll to take a look soon, definitely before the end of this week. But from what I've seen it looks good. :slightly_smiling_face:

**Comment by hsjoberg** [comment]
@dyedgreen Well, LGTM! 🚀 

Sorry again for delaying this one, code looks good to me.

**Pull request merged**
