### PR TITLE
Fix issue with databases > 2GB

### LINKED ISSUE #92: Error 22 after file reaches 2GB (WSL2)
Hi, it looks like the current version of deno-sqlite with current deno does not support files over 2GB.   
Failed at `2147352576` bytes, to be exact (2047.875MB).

Platform: Windows 10 (2004) WSL2 Ubuntu 20.04.1 kernel 4.19.128; both 64 bit

```
error: Uncaught (in promise) TypeError: Invalid argument (os error 22)
    at processResponse (core.js:224:13)
    at Object.jsonOpSync (core.js:248:12)
    at Object.seekSync (deno:cli/rt/30_files.js:13:17)
    at js_write (https://deno.land/x/sqlite@v2.3.1/build/vfs.js:61:12)
    at denoWrite (<anonymous>:0:3953)
    at pager_write_pagelist (<anonymous>:0:34829)
    at sqlite3PagerCommitPhaseOne (<anonymous>:0:26734)
    at sqlite3BtreeCommitPhaseOne (<anonymous>:0:27894)
    at sqlite3VdbeHalt (<anonymous>:0:43134)
    at sqlite3VdbeExec (<anonymous>:0:53409)
```

The code that caused it (after simplification):
```javascript
import { DB } from "https://deno.land/x/sqlite/mod.ts";

const db = new DB("data.db");
db.query("CREATE TABLE IF NOT EXISTS CachedRequest (id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT, status INTEGER, body TEXT, timestamp INTEGER, headers TEXT)");

for(var i = 1; i < 20000; i++) {
  // used for cache, but this is the first run, so nothing is cached
  const rows = [...db.query("select * from CachedRequest where url = ?", [url]).asObjects()];

  // snipped: fetch body, fill row object
  db.query("insert into CachedRequest(body, status, timestamp, headers, url) values(:body, :status, :timestamp, :headers, :url)", row);
}

db.close();
```

I can further grow the database with
```sql
insert into CachedRequest(status,url,body,timestamp,headers) select status,url,body,timestamp,headers from CachedRequest;
```
from the `sqlite3` command line utility, so this is not a WSL limitation. Perhaps something related to WASM?

### PR DESCRIPTION
**Pull request by dyedgreen**
Closes #92 

This should fix the issues that are currently experienced if trying to use a database larger than `i32::MAX` bytes. Still need to figure out a good way to test this in CI (having a >2BG db file in CI is a bit tricky...)

### CODE REVIEW

**Comment by dyedgreen** [comment]
I tested this fix locally with a ~3.5GB database, could you check it addresses the issue you're seeing as well @chanibal?

**Comment by chanibal** [comment]
I was able to insert a few megabytes of data to a 7.7GB database, so it looks like this pull request does close #92. 
Thank you for the fix.

**Review by chanibal — APPROVED** [review]

**Review by chanibal — APPROVED** [review]

**Review by chanibal — APPROVED** [review]

**Review by chanibal — APPROVED** [review]
I have no idea on how to approve this request. Marked all files as viewed, set "approve", clicked "submit review" and it still asks me for approval for merging.

**Comment by dyedgreen** [comment]
> I have no idea on how to approve this request. Marked all files as viewed, set "approve", clicked "submit review" and it still asks me for approval for merging.

Don't worry, I have to approve the it 😉

I'll look over it again tomorrow to make sure I didn't make any funny typos, and merge it then 😄

**Pull request merged**
